# Generated by Django 6.1 on 2026-08-12 14:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual weighted cost of the units dispensed, taken from the batches consumed (FEFO). Fixed at the time of sale, so a later purchase at a different price cannot change past profit.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Unit Cost'),
        ),
    ]
