# Generated by Django 6.1.1 on 2026-09-10 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0002_alter_customer_phone'),
        ('sales', '0002_saleitem_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch made this sale. Nullable only so rows recorded before multi-branch support remain valid.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', '-created_at'], name='sales_sale_branch__97dba9_idx'),
        ),
    ]
