# Generated by Django 6.1 on 2026-08-12 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, help_text='Must be unique — the phone number is how a returning customer is identified, so duplicates would split their history and loyalty points across two records.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optionally starting with +).', regex='^\\+?[0-9]{7,15}$')], verbose_name='Phone'),
        ),
    ]
