# Generated by Django 6.1 on 2026-08-12 08:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('PHARMACIST', 'Pharmacist'), ('CASHIER', 'Cashier'), ('STORE_MANAGER', 'Store Manager')], db_index=True, default='CASHIER', help_text='Determines which modules and actions this user can access.', max_length=20, verbose_name='Role')),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optionally starting with +).', regex='^\\+?[0-9]{7,15}$')], verbose_name='Phone Number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff_profiles/%Y/%m/', verbose_name='Profile Photo')),
                ('is_active_employee', models.BooleanField(default=True, help_text='Deactivate instead of deleting to preserve audit history.', verbose_name='Active Employee')),
                ('date_joined_pharmacy', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
                ('force_password_change', models.BooleanField(default=True, help_text='When set, the user is redirected to set a new password before reaching any other page. Enabled by default for new/admin-reset accounts.', verbose_name='Must Change Password')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('am', 'አማርኛ')], default='en', max_length=10, verbose_name='Preferred Language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Staff User',
                'verbose_name_plural': 'Staff Users',
                'ordering': ['-date_joined_pharmacy', 'username'],
                'indexes': [models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'), models.Index(fields=['is_active_employee'], name='accounts_us_is_acti_af7db3_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
