# Generated by Django 6.1.1 on 2026-09-10 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this person works at. Administrators may leave this blank to work across every branch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='branches.branch', verbose_name='Branch'),
        ),
    ]
