# Generated by Django 6.1.1 on 2026-09-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_branch'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The pharmacy company this person works for. Blank means platform staff, who belong to no company.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Administrator'), ('ADMIN', 'Administrator'), ('PHARMACIST', 'Pharmacist'), ('CASHIER', 'Cashier'), ('STORE_MANAGER', 'Store Manager')], db_index=True, default='CASHIER', help_text='Determines which modules and actions this user can access.', max_length=20, verbose_name='Role'),
        ),
    ]
