# Generated by Django 6.1.1 on 2026-09-12 06:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYearSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_system', models.CharField(choices=[('ETHIOPIAN', 'Ethiopian calendar'), ('GREGORIAN', 'Gregorian calendar')], default='ETHIOPIAN', help_text='Ethiopian means the year starts on a fixed Ethiopian date (Hamle 1 by default), so its Gregorian start shifts by a day around leap years. Gregorian means a fixed Gregorian date.', max_length=12, verbose_name='Calendar the year is defined in')),
                ('start_month', models.PositiveSmallIntegerField(default=11, help_text='In the chosen calendar. Ethiopian month 11 is Hamle — the start of the Ethiopian government fiscal year.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='Start Month')),
                ('start_day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Start Day')),
                ('display_calendar', models.CharField(choices=[('ETHIOPIAN', 'Ethiopian calendar'), ('GREGORIAN', 'Gregorian calendar')], default='GREGORIAN', help_text='Which calendar dates are displayed in. Independent of the fiscal year rule — you can run an Ethiopian fiscal year while showing Gregorian dates on screen.', max_length=12, verbose_name='Calendar shown to users')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_settings_updates', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Fiscal Year Settings',
                'verbose_name_plural': 'Fiscal Year Settings',
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. '2017 EC' or '2025/26'.", max_length=32, unique=True, verbose_name='Label')),
                ('start_date', models.DateField(db_index=True, verbose_name='Start Date')),
                ('end_date', models.DateField(db_index=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=8, verbose_name='Status')),
                ('calendar_system', models.CharField(choices=[('ETHIOPIAN', 'Ethiopian calendar'), ('GREGORIAN', 'Gregorian calendar')], default='ETHIOPIAN', help_text='The rule in force when this year was generated, kept for the record even if the setting later changes.', max_length=12, verbose_name='Defined In')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_years_closed', to=settings.AUTH_USER_MODEL, verbose_name='Closed By')),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='fiscal_year_ends_after_it_starts')],
            },
        ),
    ]
