# Generated by Django 6.1 on 2026-08-12 09:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='Auto-generated on save (e.g. MED-000001).', max_length=20, unique=True, verbose_name='Medicine Code')),
                ('barcode', models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode must be 6-32 characters (letters, numbers, hyphens only).', regex='^[0-9A-Za-z\\-]{6,32}$')], verbose_name='Barcode')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Medicine Name')),
                ('generic_name', models.CharField(blank=True, max_length=200, verbose_name='Generic Name')),
                ('brand', models.CharField(blank=True, max_length=150, verbose_name='Brand')),
                ('batch_number', models.CharField(blank=True, max_length=60, verbose_name='Batch Number')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='Manufacturing Date')),
                ('expiry_date', models.DateField(db_index=True, verbose_name='Expiry Date')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Cost price — visible to Administrators and Store Managers only.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Purchase Price')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Selling Price')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax (%)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount (%)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity in Stock')),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Triggers a Low Stock warning when quantity falls to or below this level.', verbose_name='Reorder Level')),
                ('unit', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('BOTTLE', 'Bottle'), ('VIAL', 'Vial'), ('TUBE', 'Tube'), ('BOX', 'Box'), ('STRIP', 'Strip'), ('ML', 'Milliliter'), ('MG', 'Milligram'), ('PIECE', 'Piece')], default='TABLET', max_length=20, verbose_name='Unit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/%Y/%m/', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicine.category', verbose_name='Category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='suppliers.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['expiry_date'], name='medicine_me_expiry__af9287_idx'), models.Index(fields=['quantity'], name='medicine_me_quantit_75cde9_idx'), models.Index(fields=['is_active'], name='medicine_me_is_acti_89af8c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='medicine_selling_price_non_negative')],
            },
        ),
    ]
