# Generated by Django 6.1 on 2026-08-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='medicine',
            name='product_type',
            field=models.CharField(choices=[('MEDICINE', 'Medicine'), ('COSMETIC', 'Cosmetic / Personal Care'), ('SUPPLY', 'Medical Supply'), ('DEVICE', 'Medical Device / Support'), ('SUPPLEMENT', 'Supplement / Vitamin'), ('BABY', 'Baby & Mother Care'), ('OTHER', 'Other')], db_index=True, default='MEDICINE', help_text='Medicines, cosmetics, dressings, devices and supplements all live in this one catalogue.', max_length=12, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='requires_prescription',
            field=models.BooleanField(db_index=True, default=False, help_text='Shows a clear warning at the till before this item is sold.', verbose_name='Requires Prescription'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, help_text='Leave blank for items that do not expire, such as a knee support or a blood-pressure monitor.', null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('BOTTLE', 'Bottle'), ('VIAL', 'Vial'), ('TUBE', 'Tube'), ('BOX', 'Box'), ('STRIP', 'Strip'), ('ML', 'Milliliter'), ('MG', 'Milligram'), ('PIECE', 'Piece'), ('PACK', 'Pack'), ('ROLL', 'Roll'), ('PAIR', 'Pair'), ('SACHET', 'Sachet'), ('JAR', 'Jar'), ('UNIT', 'Unit')], default='TABLET', max_length=20, verbose_name='Unit'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['product_type'], name='medicine_me_product_b8a6bd_idx'),
        ),
    ]
