# Generated by Django 6.1.1 on 2026-09-10 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('medicine', '0002_alter_medicine_options_medicine_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='catalogue_product',
            field=models.ForeignKey(blank=True, help_text='The standard catalogue record this stock item is registered against. Linking keeps naming consistent and makes group reporting possible. Leave blank only for something genuinely not in the catalogue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='catalogue.catalogueproduct', verbose_name='Catalogue Product'),
        ),
    ]
