# Generated by Django 6.1.1 on 2026-09-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicine_catalogue_product'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The pharmacy company that owns this record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The pharmacy company that owns this record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organization'),
        ),
    ]
