# Generated by Django 6.1 on 2026-08-12 12:35

import apps.settings_app.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=apps.settings_app.models.default_pharmacy_name, max_length=200, verbose_name='Pharmacy Name')),
                ('logo', models.ImageField(blank=True, help_text='Shown on invoices and shelf labels.', null=True, upload_to='pharmacy/', verbose_name='Logo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('license_number', models.CharField(blank=True, help_text='Pharmacy operating licence, printed on invoices.', max_length=80, verbose_name='Licence Number')),
                ('tin_number', models.CharField(blank=True, help_text='Taxpayer identification number, printed on invoices.', max_length=40, verbose_name='TIN Number')),
                ('currency', models.CharField(default=apps.settings_app.models.default_currency, max_length=10, verbose_name='Currency')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Pre-filled on new medicines. Existing records keep their own rate.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Default Tax Rate (%)')),
                ('large_sale_threshold', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Sales at or above this value raise a notification.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Large Sale Alert Threshold')),
                ('loyalty_points_per_unit', models.PositiveIntegerField(default=100, help_text='Amount a customer must spend to earn one loyalty point.', verbose_name='Currency per Loyalty Point')),
                ('invoice_prefix', models.CharField(default=apps.settings_app.models.default_invoice_prefix, help_text='Applied to new invoices only; existing numbers never change.', max_length=10, verbose_name='Invoice Prefix')),
                ('invoice_footer', models.TextField(blank=True, default='Thank you for your purchase.', help_text='Printed at the bottom of every customer invoice.', verbose_name='Invoice Footer')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Pharmacy Settings',
                'verbose_name_plural': 'Pharmacy Settings',
            },
        ),
    ]
