# Generated by Django 6.1.1 on 2026-09-15 09:20

import django.db.models.deletion
from django.db import migrations, models


def attach_legacy_settings_to_the_default_organization(apps, schema_editor):
    """Before this migration, PharmacySettings was a global singleton
    (pk=1) — one row, shared by every pharmacy. If that row exists and
    there's exactly one organization on the platform, it almost certainly
    represents that organization's settings, so attach it rather than
    leaving it orphaned. With zero or several organizations there's no
    single correct guess, so it's left unattached — harmless (it just
    won't be loaded by anyone until reassigned), and each organization
    gets a fresh settings row seeded from its own name on first access
    regardless (see PharmacySettings.load).
    """
    PharmacySettings = apps.get_model("settings_app", "PharmacySettings")
    Organization = apps.get_model("organizations", "Organization")

    legacy = PharmacySettings.objects.filter(pk=1, organization__isnull=True).first()
    if legacy is None:
        return
    orgs = list(Organization.objects.all()[:2])
    if len(orgs) == 1:
        legacy.organization = orgs[0]
        legacy.save(update_fields=["organization"])


def unattach(apps, schema_editor):
    """Reverse: just detach — the row itself predates this migration and
    shouldn't be deleted by reversing it."""
    PharmacySettings = apps.get_model("settings_app", "PharmacySettings")
    PharmacySettings.objects.filter(pk=1).update(organization=None)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_payment'),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='organization',
            field=models.OneToOneField(blank=True, help_text='Blank only for a legacy row that predates per-pharmacy settings.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.RunPython(
            attach_legacy_settings_to_the_default_organization, unattach
        ),
    ]
