# Generated by Django 6.1 on 2026-08-12 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Stock Adjustment'), ('TRANSFER', 'Stock Transfer')], db_index=True, max_length=12, verbose_name='Movement Type')),
                ('quantity', models.PositiveIntegerField(help_text='For Stock Adjustment, this is the new counted quantity, not a delta.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('quantity_before', models.PositiveIntegerField(editable=False, verbose_name='Quantity Before')),
                ('quantity_after', models.PositiveIntegerField(editable=False, verbose_name='Quantity After')),
                ('destination', models.CharField(blank=True, help_text='Required for Stock Transfer — the receiving branch or location.', max_length=200, verbose_name='Destination')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='medicine.medicine', verbose_name='Medicine')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'), models.Index(fields=['created_at'], name='inventory_s_created_05ebf5_idx')],
            },
        ),
    ]
