# Generated by Django 6.1 on 2026-08-12 14:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('medicine', '0001_initial'),
        ('purchases', '0002_purchaseitem_new_selling_price'),
        ('sales', '0002_saleitem_unit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=60, verbose_name='Batch Number')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='What this batch actually cost per unit. Never overwritten.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Unit Cost')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='The price set when this batch arrived, kept for reference. The price actually charged is snapshotted on each sale line.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Selling Price at Intake')),
                ('quantity_received', models.PositiveIntegerField(verbose_name='Quantity Received')),
                ('quantity_remaining', models.PositiveIntegerField(db_index=True, verbose_name='Quantity Remaining')),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Expiry Date')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Received')),
                ('source', models.CharField(default='PURCHASE', help_text='PURCHASE, OPENING (pre-existing stock), ADJUSTMENT or RETURN.', max_length=20, verbose_name='Source')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='medicine.medicine', verbose_name='Medicine')),
                ('purchase_item', models.ForeignKey(blank=True, help_text='The purchase that brought this batch in, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='purchases.purchaseitem', verbose_name='Purchase Line')),
            ],
            options={
                'verbose_name': 'Stock Batch',
                'verbose_name_plural': 'Stock Batches',
                'ordering': ['expiry_date', 'received_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SaleItemCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Copied from the batch so the record survives batch deletion.', max_digits=10, verbose_name='Unit Cost')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='sales.saleitem', verbose_name='Sale Line')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_allocations', to='inventory.stockbatch', verbose_name='Batch')),
            ],
            options={
                'verbose_name': 'Sale Line Cost Allocation',
                'verbose_name_plural': 'Sale Line Cost Allocations',
            },
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['medicine', 'quantity_remaining'], name='inventory_s_medicin_70b674_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='inventory_s_expiry__709598_idx'),
        ),
    ]
