# Generated by Django 6.1.1 on 2026-09-10 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0002_stockbatch_saleitemcost_and_more'),
        ('medicine', '0002_alter_medicine_options_medicine_product_type_and_more'),
        ('purchases', '0003_purchaseinvoice_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Batches are held at a branch: the same product can sit in two branches at different costs, and each must be costed separately.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch whose stock this movement affects.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_branch',
            field=models.ForeignKey(blank=True, help_text='For a Stock Transfer: the branch receiving the goods. Stock is removed here and added there in one operation, at the same cost.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='branches.branch', verbose_name='Destination Branch'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['branch', 'medicine', 'quantity_remaining'], name='inventory_s_branch__656ec8_idx'),
        ),
    ]
