# Generated by Django 6.1.1 on 2026-09-10 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_create_main_branch'),
        ('inventory', '0003_stockbatch_branch_stockmovement_branch_and_more'),
        ('medicine', '0002_alter_medicine_options_medicine_product_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=24, unique=True, verbose_name='Reference')),
                ('status', models.CharField(choices=[('DRAFT', 'In progress'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=10, verbose_name='Status')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to='branches.branch', verbose_name='Branch')),
                ('category', models.ForeignKey(blank=True, help_text='Limit the count to one category, for counting a section at a time. Leave blank to count everything at this branch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktakes', to='medicine.category', verbose_name='Category')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktakes_posted', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktakes_started', to=settings.AUTH_USER_MODEL, verbose_name='Started By')),
            ],
            options={
                'verbose_name': 'Stocktake',
                'verbose_name_plural': 'Stocktakes',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('PURCHASE', 'Purchase received'), ('SALE', 'Sale'), ('SALE_VOID', 'Sale voided'), ('PURCHASE_DELETE', 'Purchase deleted'), ('STOCK_IN', 'Stock in'), ('STOCK_OUT', 'Stock out'), ('ADJUSTMENT', 'Adjustment'), ('STOCKTAKE', 'Stocktake'), ('TRANSFER_OUT', 'Transfer out'), ('TRANSFER_IN', 'Transfer in'), ('OPENING', 'Opening balance'), ('RETURN', 'Customer return'), ('OTHER', 'Other')], db_index=True, max_length=20, verbose_name='Cause')),
                ('quantity_change', models.IntegerField(help_text='Positive for stock coming in, negative for stock going out.', verbose_name='Change')),
                ('balance_before', models.PositiveIntegerField(verbose_name='Balance Before')),
                ('balance_after', models.PositiveIntegerField(verbose_name='Balance After')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit of the stock that moved, where known.', max_digits=10, null=True, verbose_name='Unit Cost')),
                ('reference', models.CharField(blank=True, db_index=True, help_text='The document behind this change, e.g. INV-000042 or PUR-000007.', max_length=60, verbose_name='Reference')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='branches.branch', verbose_name='Branch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='medicine.medicine', verbose_name='Product')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='By')),
            ],
            options={
                'verbose_name': 'Stock Ledger Entry',
                'verbose_name_plural': 'Stock Ledger',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['branch', 'medicine', '-created_at'], name='inventory_s_branch__3c4921_idx'), models.Index(fields=['source'], name='inventory_s_source_441e2b_idx'), models.Index(fields=['reference'], name='inventory_s_referen_4d4813_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockTakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField(help_text='System figure frozen when the stocktake was opened.', verbose_name='Expected')),
                ('counted_quantity', models.PositiveIntegerField(blank=True, help_text='Leave blank until this product has actually been counted.', null=True, verbose_name='Counted')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_lines', to='medicine.medicine', verbose_name='Product')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake')),
            ],
            options={
                'verbose_name': 'Stocktake Line',
                'verbose_name_plural': 'Stocktake Lines',
                'ordering': ['medicine__name'],
                'constraints': [models.UniqueConstraint(fields=('stocktake', 'medicine'), name='unique_product_per_stocktake')],
            },
        ),
    ]
