# Generated by Django 6.1.1 on 2026-09-10 12:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Catalogue Category',
                'verbose_name_plural': 'Catalogue Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(db_index=True, help_text='International non-proprietary name, e.g. Paracetamol. This is the name reporting groups by, so it must not carry a brand.', max_length=200, verbose_name='Generic Name (INN)')),
                ('brand_name', models.CharField(blank=True, db_index=True, help_text='Leave blank for a generic entry.', max_length=200, verbose_name='Brand Name')),
                ('strength', models.CharField(blank=True, help_text='Include units, e.g. 500mg, 125mg/5ml, 0.9%.', max_length=60, verbose_name='Strength')),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('SOLUTION', 'Solution'), ('INJECTION', 'Injection'), ('INFUSION', 'Infusion'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('GEL', 'Gel'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('SUPPOSITORY', 'Suppository'), ('PESSARY', 'Pessary'), ('PATCH', 'Patch'), ('POWDER', 'Powder'), ('SACHET', 'Sachet'), ('DEVICE', 'Device'), ('DRESSING', 'Dressing'), ('OTHER', 'Other')], db_index=True, default='TABLET', max_length=20, verbose_name='Dosage Form')),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('TOPICAL', 'Topical'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('OPHTHALMIC', 'Eye'), ('OTIC', 'Ear'), ('NASAL', 'Nasal'), ('INHALED', 'Inhaled'), ('RECTAL', 'Rectal'), ('VAGINAL', 'Vaginal'), ('NA', 'Not applicable')], default='ORAL', max_length=12, verbose_name='Route')),
                ('atc_code', models.CharField(blank=True, db_index=True, help_text='WHO Anatomical Therapeutic Chemical code, e.g. N02BE01.', max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid ATC code, e.g. N02BE01 or a partial code like N02BE.', regex='^[A-Z]\\d{2}[A-Z]{2}\\d{2}$|^[A-Z]\\d{2}[A-Z]{0,2}$|^$')], verbose_name='ATC Code')),
                ('schedule', models.CharField(choices=[('OTC', 'Over the counter'), ('POM', 'Prescription only'), ('CONTROLLED', 'Controlled substance')], db_index=True, default='OTC', help_text='Drives the prescription warning at the till when a pharmacy registers this product.', max_length=12, verbose_name='Legal Class')),
                ('product_type', models.CharField(default='MEDICINE', help_text='Matches the pharmacy product types: MEDICINE, COSMETIC, SUPPLY, DEVICE, SUPPLEMENT, BABY, OTHER.', max_length=12, verbose_name='Product Type')),
                ('default_unit', models.CharField(default='TABLET', help_text='Pre-fills the unit when a pharmacy registers this product.', max_length=20, verbose_name='Default Unit')),
                ('pack_size', models.CharField(blank=True, help_text="As sold, e.g. 'Box of 100', 'Bottle of 100ml'.", max_length=60, verbose_name='Pack Size')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Manufacturer')),
                ('country_of_origin', models.CharField(blank=True, max_length=80, verbose_name='Country of Origin')),
                ('efda_registration_number', models.CharField(blank=True, db_index=True, help_text='Left blank unless taken from the EFDA register — never guessed.', max_length=60, verbose_name='EFDA Registration Number')),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Manufacturer barcode, if the pack carries one.', max_length=64, verbose_name='Barcode (GTIN)')),
                ('is_essential', models.BooleanField(db_index=True, default=False, help_text='On the essential medicines list, so shortages matter more.', verbose_name='Essential Medicine')),
                ('requires_cold_chain', models.BooleanField(default=False, help_text='Must be kept refrigerated — shown as a warning on stock pages.', verbose_name='Requires Cold Chain')),
                ('data_source', models.CharField(choices=[('EFDA', 'EFDA register'), ('WHO_EML', 'WHO Essential Medicines List'), ('STARTER', 'Bundled starter set (verify before regulatory use)'), ('LOCAL', 'Added locally')], db_index=True, default='LOCAL', max_length=12, verbose_name='Data Source')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.cataloguecategory', verbose_name='Therapeutic Category')),
            ],
            options={
                'verbose_name': 'Catalogue Product',
                'verbose_name_plural': 'Catalogue Products',
                'ordering': ['generic_name', 'strength', 'brand_name'],
                'indexes': [models.Index(fields=['generic_name', 'strength'], name='catalogue_c_generic_e0f784_idx'), models.Index(fields=['schedule'], name='catalogue_c_schedul_8c1181_idx'), models.Index(fields=['data_source'], name='catalogue_c_data_so_f35f7c_idx')],
                'constraints': [models.UniqueConstraint(fields=('generic_name', 'strength', 'dosage_form', 'brand_name'), name='unique_catalogue_identity')],
            },
        ),
    ]
