# Generated by Django 6.1.1 on 2026-09-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueproduct',
            name='strength',
            field=models.CharField(blank=True, help_text="Include units, e.g. 500mg, 125mg/5ml, 0.9%. Can hold several strengths for the same form (e.g. a source list's 100mg, 200mg, 400mg for one tablet) rather than forcing one row per strength.", max_length=200, verbose_name='Strength'),
        ),
    ]
