# Generated by Django 6.1 on 2026-08-12 14:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='new_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Optional. If this intake changes what you charge, set the new price here — it updates the medicine's current price. Sales already made keep the price they were sold at.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='New Selling Price'),
        ),
    ]
