# Generated by Django 6.1.1 on 2026-09-10 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('purchases', '0002_purchaseitem_new_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch these goods were delivered to. Stock is added there.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='branches.branch', verbose_name='Receiving Branch'),
        ),
    ]
