# Generated by Django 6.1.1 on 2026-09-10 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0002_alter_medicine_options_medicine_product_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Branch Name')),
                ('code', models.CharField(editable=False, help_text='Auto-generated, e.g. BR-001. Appears on invoices and reports.', max_length=12, unique=True, verbose_name='Branch Code')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s\\-()]{7,20}$')], verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='City / Town')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('license_number', models.CharField(blank=True, help_text="This branch's own operating licence, printed on its invoices.", max_length=80, verbose_name='Licence Number')),
                ('invoice_prefix', models.CharField(blank=True, help_text="Optional. Overrides the pharmacy-wide prefix so each branch's invoice numbers are distinguishable, e.g. BOL-.", max_length=10, verbose_name='Invoice Prefix')),
                ('is_main', models.BooleanField(default=False, help_text='The default branch. Exactly one branch is the main one.', verbose_name='Main Branch')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive branches keep their history but cannot record new sales, purchases or stock movements.', verbose_name='Active')),
                ('opened_on', models.DateField(blank=True, null=True, verbose_name='Opened On')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='Branch Manager')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Quantity in Stock')),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Per branch, so a busy branch can reorder earlier than a quiet one.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reorder Level')),
                ('shelf_location', models.CharField(blank=True, help_text="Where this sits in this particular branch, e.g. 'Aisle 3, Shelf B'.", max_length=60, verbose_name='Shelf / Location')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='branches.branch', verbose_name='Branch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='medicine.medicine', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Branch Stock Level',
                'verbose_name_plural': 'Branch Stock Levels',
                'ordering': ['branch__name', 'medicine__name'],
                'indexes': [models.Index(fields=['branch', 'quantity'], name='branches_br_branch__f220ff_idx'), models.Index(fields=['medicine'], name='branches_br_medicin_c24f50_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'medicine'), name='unique_stock_per_branch_product')],
            },
        ),
    ]
