# Generated by Django 6.1.1 on 2026-09-12 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='Auto-generated, e.g. ORG-001.', max_length=12, unique=True, verbose_name='Organization Code')),
                ('legal_name', models.CharField(help_text='As registered. Appears on tax invoices and financial statements.', max_length=200, verbose_name='Legal Name')),
                ('trade_name', models.CharField(blank=True, help_text='The name customers know. Falls back to the legal name.', max_length=200, verbose_name='Trade Name')),
                ('tin', models.CharField(blank=True, max_length=32, verbose_name='TIN')),
                ('license_number', models.CharField(blank=True, max_length=80, verbose_name='Licence Number')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s\\-()]{7,20}$')], verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('region', models.CharField(blank=True, max_length=80, verbose_name='Region')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='City')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/', verbose_name='Logo')),
                ('currency', models.CharField(default='ETB', help_text='ISO code. Used on every money figure for this company.', max_length=8, verbose_name='Currency')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('am', 'አማርኛ')], default='en', max_length=8, verbose_name='Default Language')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', help_text='Suspended companies keep their data but cannot trade. Used later for non-payment.', max_length=12, verbose_name='Status')),
                ('is_platform_owner', models.BooleanField(default=False, help_text='Marks the organization that operates the platform itself. There is at most one.', verbose_name='Platform Owner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['legal_name'],
            },
        ),
    ]
