# Generated by Django 6.1.1 on 2026-09-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_default_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_branches',
            field=models.PositiveIntegerField(blank=True, help_text='Optional cap tied to their plan. Leave blank for unlimited.', null=True, verbose_name='Branch Limit'),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(blank=True, help_text='Optional cap tied to their plan. Leave blank for unlimited.', null=True, verbose_name='Staff Limit'),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('TRIAL', 'Free Trial'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='TRIAL', max_length=12, verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan_notes',
            field=models.CharField(blank=True, help_text='Manual record until real payment processing exists — e.g. "Paid via bank transfer, receipt #1234, covers Sep 2026."', max_length=255, verbose_name='Plan / Billing Notes'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_ends_at',
            field=models.DateField(blank=True, help_text="When this pharmacy's current paid period ends. Leave blank for an open-ended account.", null=True, verbose_name='Subscription Ends'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', help_text="Suspended companies keep their data but cannot trade — their staff are signed out immediately and can't log back in until this changes.", max_length=12, verbose_name='Status'),
        ),
    ]
