# Generated by Django 6.1.1 on 2026-09-15 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_plan_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='ETB', max_length=8, verbose_name='Currency')),
                ('provider', models.CharField(choices=[('MANUAL', 'Manually recorded'), ('CHAPA', 'Chapa')], default='MANUAL', max_length=12, verbose_name='Provider')),
                ('provider_reference', models.CharField(blank=True, help_text="A gateway's own transaction id, once one exists. Blank for manually recorded payments.", max_length=120, verbose_name='Provider Reference')),
                ('status', models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='SUCCESSFUL', max_length=12, verbose_name='Status')),
                ('plan_at_payment', models.CharField(choices=[('TRIAL', 'Free Trial'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=12, verbose_name='Plan Paid For')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(help_text="The organization's subscription end date is set to this on a successful payment.", verbose_name='Period End')),
                ('notes', models.CharField(blank=True, help_text='E.g. "Bank transfer, receipt #1234" or "Telebirr screenshot verified by Abebe".', max_length=255, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organizations.organization', verbose_name='Organization')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Blank for a payment a gateway confirmed automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
