# Generated by Django 6.1 on 2026-08-12 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('EXPIRED', 'Expired Medicine'), ('EXPIRING', 'Expiring Soon'), ('NEW_PURCHASE', 'New Purchase'), ('LARGE_SALE', 'Large Sale'), ('PENDING_PAYMENT', 'Pending Payment'), ('SYSTEM', 'System')], db_index=True, max_length=20, verbose_name='Type')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=10, verbose_name='Severity')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('link', models.CharField(blank=True, help_text='Relative URL the notification points to, if any.', max_length=300, verbose_name='Link')),
                ('target_roles', models.CharField(blank=True, help_text='Comma-separated role codes. Blank means all staff.', max_length=120, verbose_name='Target Roles')),
                ('dedupe_key', models.CharField(help_text='Identifies what this alert is about, so refreshing does not create duplicates.', max_length=200, unique=True, verbose_name='Deduplication Key')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Cleared automatically when the underlying condition no longer holds (e.g. stock was replenished).', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='notificatio_is_acti_ff0c71_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Read Marker',
                'verbose_name_plural': 'Notification Read Markers',
                'constraints': [models.UniqueConstraint(fields=('notification', 'user'), name='unique_notification_read_per_user')],
            },
        ),
    ]
