# Generated by Django 6.1.1 on 2026-09-10 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_create_main_branch'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this alert concerns. Blank means it applies pharmacy-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='branches.branch', verbose_name='Branch'),
        ),
    ]
